show_analysis_paths: False
show_analysis_time: False
intro_text: False
custom_data:
  gene_coverage:
    file_format: "csv"
    section_name: "Gene Coverage"
    plot_type: "linegraph"
    pconfig:
      id: "gene_coverage_lineplot"
      title: "Gene Coverage"
      ylab: "Genes"
      xlab: "% Positions Covered"
      ymax: 388
      ymin: 0
      tt_label: "{point.y} genes have ≥ {point.x}% positions covered"
sp:
  gene_coverage:
    fn: "*.csv"
